petstagram/common/urls.py
from django.urls import path
from petstagram.common import views


urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('like/<int:photo_id>/', views.likes_functionality, name='like'),
    path('share/<int:photo_id>/', views.share_functionality, name='share'),
    path('comment/<int:photo_id>/', views.comment_functionality, name='comment')
]

petstagram/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class Comment(models.Model):
    class Meta:
        indexes = [
            models.Index(fields=['date_time_of_publication']),
        ]
        ordering = ['-date_time_of_publication']

    text = models.TextField(
        max_length=300,
    )

    date_time_of_publication = models.DateTimeField(
        auto_now_add=True,
    )

    to_photo = models.ForeignKey(
        to=Photo,
        on_delete=models.CASCADE,
    )


class Like(models.Model):
    to_photo = models.ForeignKey(
        to=Photo,
        on_delete=models.CASCADE,
    )

petstagram/common/forms.py
from django import forms
from petstagram.common.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Add comment...'}),
        }


class SearchForm(forms.Form):
    pet_name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search by pet name...',
            }
        )
    )

petstagram/common/views.py
from django.shortcuts import render, redirect, resolve_url
from pyperclip import copy
from django.views.generic import ListView
from petstagram.common.forms import CommentForm, SearchForm
from petstagram.common.models import Like
from petstagram.photos.models import Photo


class HomePage(ListView):
    model = Photo
    template_name = 'common/home-page.html'
    context_object_name = 'all_photos'  # by default is object_list and photos
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['comment_form'] = CommentForm()
        context['search_form'] = SearchForm(self.request.GET)

        return context

    def get_queryset(self):
        queryset = super().get_queryset()  # All objects
        pet_name = self.request.GET.get('pet_name')

        if pet_name:
            queryset = queryset.filter(  # Filter the objects
                tagged_pets__name__icontains=pet_name
            )

        return queryset


def likes_functionality(request, photo_id: int):
    liked_object = Like.objects.filter(
        to_photo_id=photo_id
    ).first()

    if liked_object:
        liked_object.delete()
    else:
        like = Like(to_photo_id=photo_id)
        like.save()

    return redirect(request.META.get('HTTP_REFERER') + f'#{photo_id}')


def share_functionality(request, photo_id: int):
    copy(request.META.get('HTTP_HOST') + resolve_url('photo-details', photo_id))
    # HTTP_HOST = http://127.0.0.1/   + photos/<int:pk>/ => http://127.0.0.1/photos/<int:pk>/

    return redirect(request.META.get('HTTP_REFERER') + f'#{photo_id}')


def comment_functionality(request, photo_id: int):
    if request.POST:
        photo = Photo.objects.get(pk=photo_id)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.to_photo = photo
            comment.save()

        return redirect(request.META.get('HTTP_REFERER') + f'#{photo_id}')

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <title>Petstagram</title>
</head>
<body>

<header>
    {% include 'common/nav.html' %}
</header>

<main>

    {% block content %}
    {% endblock %}

</main>

<div class="footer">
       <span class="footer-section">
          © 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
       </span>
</div>

templates/common/home-page.html
{% extends 'common/base.html' %} {% load url_query_append %} {% load static %}
{% block content %}
<div class="container">
  <div class="col-9">
    <!-- Start Searchbar Form -->
    <form class="searchbar">
      {{ search_form }}
      <button>
        <img src="{% static '/images/search.png' %}" height="18" alt="img2" />
      </button>
    </form>
    <!-- End Searchbar Form -->
    {% for photo in page_obj %} {% include 'common/pet-posts.html' %} {%endfor%}

    <!-- Start Pagination -->
    <div class="pagination">
      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>

      <span class="step-links-buttons">
        <!-- If there are previous and next photos -->
        {% if page_obj.has_previous and page_obj.has_next %}
        <a
          href="?{% url_query_append_tag request 'page' page_obj.previous_page_number %}"
        >
          <i class="fa-solid fa-arrow-left"></i>
        </a>
        <a
          href="?{% url_query_append_tag request 'page' page_obj.next_page_number %}"
        >
          <i class="fa-solid fa-arrow-right"></i>
        </a>

        <!-- If there are only previous photos -->
        {% elif page_obj.has_previous %}
        <a
          href="?{% url_query_append_tag request 'page' page_obj.previous_page_number %}"
        >
          <i class="fa-solid fa-arrow-left"></i>
        </a>

        <!-- If there are only next photos -->
        {% elif page_obj.has_next %}
        <a
          href="?{% url_query_append_tag request 'page' page_obj.next_page_number %}"
        >
          <i class="fa-solid fa-arrow-right"></i>
        </a>
        {% endif %}
      </span>
    </div>
    <!-- End Pagination -->
  </div>
</div>
{% endblock %}

templates/common/nav.html
{% load static %}

<nav class="navbar">
    <div class="container">
        <div class="logo">
            <!-- Link to Home Page -->
            <a href="#">
                <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}"
                     alt="img1">
            </a>

            <!-- Link to Home Page -->
            <a class="home" href="{% url 'home' %}">
                <i>Petstagram</i>
            </a>
        </div>

        <div class="nav-links">
            <ul class="nav-group">
                <li class="nav-item">

                    <!-- Link to Add Pet Page -->
                    <a href="{% url 'add-pet' %}">
                        <i>Add Pet</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Add Photo Page -->
                    <a href="{% url 'photo-add' %}">
                        <i>Add Photo</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Login Page -->
                    <a href="{% url 'login' %}">
                        <i>Login</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Register Page -->
                    <a href="{% url 'register' %}">
                        <i>Register</i>
                    </a>
                </li>
                <li class="nav-item">

                    <!-- Link to Profile Page -->
                    <a href="#">
                        <i>Profile</i>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#">
                        <i>Logout</i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/common/pet-posts.html
{% load static %}

<div class="card">
    <div class="top">
        <!-- User Details and image location -->
        <div class="userDetails">
            <a href="profile details">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="/static/images/person.png" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="profile details">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- user username -->
                </a>
                <br>
                <!-- if the photo has location -->
                {% if photo.location %}
                    <span>{{ photo.location }}</span>
                {% endif %}
                
                {% if photo_page %}
                <div class="edit-delete-btns">
    
                    <!-- Link to Edit Pet Photo Page -->
                    <a href="{% url 'photo-edit' photo.pk %}">
                        <img class="edit-img" src="{% static '/images/edit-pen-icon-6.jpg' %}"
                             alt="edit button">
                    </a>
    
                    <!-- Link to Delete Pet Photo Page -->
                    <a href="{% url 'photo-delete' photo.pk %}">
                        <img class="bin-img" src="{% static '/images/icon-remove-22.jpg' %}"
                             alt="bin button">
                    </a>
                </div>
                {% endif %}
            </h3>
        </div>
        <!--  -->
    </div>
    <!-- Post image -->
    <div class="imgBx" id="{{ photo.pk }}">
        <img src="{{ photo.photo.url }}" alt="post" class="cover">
    </div>
    <!-- -->

    <div class="bottom">
        <!-- like and share buttons -->
        <div class="actionBtns">
            <div class="left">
                    <span class="heart">
                        <a href="{% url 'like' photo.pk %}">
                          {% if photo.like_set.all %}
                              <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                           {% else %}
                               <i class="fa-regular fa-heart"></i>
                           {% endif %}                   
                        </a>
                    </span>
                <a href="{% url 'share' photo.id %}">
                    <i class="fa-solid fa-share"></i>
                </a>

            </div>
        </div>
        <!-- -->

        <a href="#">
            <p class="likes">{{ photo.like_set.count }} likes</p>
        </a>

        {% for pet in photo.tagged_pets.all %}
            <!-- Link to First Tagged Pet Details Page-->
            <a href="{% url 'pet-details' "username" pet.slug %}">
                <p class="message">
                    <b>{{ pet.name }}</b>
                </p>
            </a>
        {% endfor %}
    
        {% if photo_page %}
        <!-- Photo description -->
        <p class="pet-details">{{ photo.description }}</p>
        {% else %}
            <a href="{% url 'photo-details' photo.pk %}">
                <h4 class="details">See details</h4>
            </a>
        {% endif %}

        <h5 class="postTime">{{ photo.date_of_publication }}</h5>

        {% if photo_page %}
         {% for comment in comments %}
            <div class="comments">
                <div class="top">
                    <div class="userDetails">
                        <div class="comment-data">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <!-- User Profile Image -->
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                            <p>
                                <!-- Link to User Profile Details Page-->
                                <!-- User First and/or Last Name or username-->
                                <a href="">Steven Ivanov</a>
                                <!-- User Comment -->
                                {{ comment.text }}
                            </p>
                        </div>
                        <span>{{ comment.date_time_of_publication }}</span>
                    </div>
                </div>
            </div>
            <!-- End Comments Section -->
        {% endfor %}

        {% endif %}
    
        <!-- add comments section -->
        <div class="addComments">

            <form method="post" action="{% url 'comment' photo.pk %}">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit">Post</button>
            </form>
        </div>
        <!--  -->
    </div>
</div>